version: '27.0.3'

services:
  laboratorio-opoinf:
    build: laboratorio_opoinf
    mem_limit: 512m
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web
    environment:
      - DB_DDLAUTO
      - DB_DRIVER
      - DB_PASSWORD
      - DB_PLATAFORM
      - DB_SHOWSQL
      - DB_URL
      - DB_USERNAME
      - JWT_ACCESS_TOKEN_EXPIRATION
      - JWT_KEY
      - JWT_REFRESH_TOKEN_EXPIRATION
      - MAIL_HOST
      - MAIL_PASSWORD
      - MAIL_PORT
      - MAIL_SMTPAUTH
      - MAIL_SMTPSTARTTLSENABLE
      - MAIL_USERNAME
    restart: always